---
name: Lint Code Base
# for more information, see
# https://github.com/github/super-linter
on:
  workflow_call:
    secrets:
      GITHUB_TOKEN_CALLER:
        description: 'A GitHub Action token passed from the caller workflow'
        required: true

jobs:
  lint:
    name: Lint Code Base (Except R)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of 
          # changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v5.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_CALLER }}
          LINTER_RULES_PATH: .
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_NATURAL_LANGUAGE: false
          # terragrunt must not pick up on docker-bake.hcl, blocked by
          # https://github.com/github/super-linter/issues/2537
          VALIDATE_TERRAGRUNT: false
          # lintr isn't just static code analysis, it calls eval, parse
          # so it needs the project runtime for a complete analysis
          # so it's best to run it with other cicd
          VALIDATE_R: false
